# Generated by Django 5.2.5 on 2025-08-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_gb', models.IntegerField()),
                ('sistema_operacional', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos_hardware', models.ManyToManyField(related_name='modelos_llm', to='compatibilidade.configuracaohardware')),
            ],
        ),
    ]
